// ChatGPT / Codex: contract regressions frozen before the Claude guard repair.
// Run against an alternate original module with --module /absolute/path.mjs.
import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
const arg = (name) => { const i = process.argv.indexOf(name); return i < 0 ? null : process.argv[i + 1]; };
const target = arg('--module') ? pathToFileURL(arg('--module')) : new URL('./guard.mjs', import.meta.url);
const { guard, combine } = await import(target);
const labels = JSON.parse(readFileSync(new URL('./schema.json', import.meta.url))).properties.items.items.properties.term.enum;
const note = 'The child has fever for two days. Mother has cough.';
const item = (extra = {}) => ({term:'fever', status:'stated', evidence:'The child has fever for two days', duration_days:2, ...extra});
const g = (it, text = note) => guard({items:[it]}, text, labels);
const tests = [];
const check = (name, fn) => { try {fn(); tests.push({name,pass:true});} catch(e) {tests.push({name,pass:false,error:e.message});} };
check('Valid exact quote survives unchanged', () => assert.equal(g(item()).accepted[0].evidence,item().evidence));
check('Case-changed quote rejected', () => assert.equal(g(item({evidence:'the child has fever for two days'})).accepted.length,0));
check('Whitespace-changed quote rejected', () => assert.equal(g(item({evidence:'The child  has fever for two days'})).accepted.length,0));
check('Punctuation-changed quote rejected', () => assert.equal(g(item({evidence:'The child has fever for two days!'})).accepted.length,0));
check('Quote marks cannot be silently removed', () => assert.equal(g(item({evidence:'"The child has fever for two days"'})).accepted.length,0));
check('Unicode quote preserved', () => assert.equal(g(item({evidence:'Mtoto ana homa “leo”',duration_days:null}),'Mtoto ana homa “leo”.').accepted[0].evidence,'Mtoto ana homa “leo”'));
check('Known exact quote receives original offsets', () => { const a=g(item()).accepted[0];assert.equal(note.slice(a.evidence_start,a.evidence_end),a.evidence); });
check('Repeated quote exposes ambiguity', () => {const r=g(item({evidence:'fever',duration_days:null}),'fever, fever');assert.equal(r.accepted[0].evidence_start,null);assert.ok(r.warnings.some(w=>w.reason==='evidence_ambiguous'));});
check('Evidence must be a string', () => assert.equal(g(item({evidence:23,duration_days:null}),'23').accepted.length,0));
check('Evidence cannot exceed schema maximum', () => assert.equal(g(item({evidence:'x'.repeat(201),duration_days:null}),'x'.repeat(201)).accepted.length,0));
check('Unknown term rejected', () => assert.equal(g(item({term:'malaria'})).accepted.length,0));
check('Unknown status rejected', () => assert.equal(g(item({status:'severe'})).accepted.length,0));
check('Extra clinical text property rejected', () => assert.equal(g(item({advice:'give medicine'})).accepted.length,0));
check('Extra root property rejected', () => assert.equal(guard({items:[item()],diagnosis:'malaria'},note,labels).accepted.length,0));
check('Missing required duration rejected', () => {const a=item();delete a.duration_days;assert.equal(g(a).accepted.length,0);});
check('String duration rejected', () => assert.equal(g(item({duration_days:'2'})).accepted.length,0));
check('Fractional duration rejected', () => assert.equal(g(item({duration_days:2.5})).accepted.length,0));
check('Out-of-range duration rejected', () => assert.equal(g(item({evidence:'fever for 366 days',duration_days:366}),'fever for 366 days').accepted.length,0));
check('Unsupported duration dropped with warning', () => {const r=g(item({duration_days:3}));assert.equal(r.accepted[0].duration_days,null);assert.ok(r.warnings.some(w=>w.reason==='duration_dropped'));});
check('Denied term cannot retain duration', () => assert.equal(g(item({status:'denied'})).accepted[0].duration_days,null));
check('Conflicting duplicate term is never first-wins', () => assert.equal(guard({items:[item(),item({status:'denied'})]},note,labels).accepted.length,0));
check('Items above schema limit reject whole response', () => assert.equal(guard({items:Array.from({length:11},()=>item())},note,labels).accepted.length,0));
check('Markdown JSON fence accepted explicitly', () => assert.equal(guard('```json\n'+JSON.stringify({items:[item()]})+'\n```',note,labels).accepted.length,1));
check('Prose around JSON rejected', () => assert.equal(guard('Here you go '+JSON.stringify({items:[item()]}),note,labels).accepted.length,0));
check('Empty term list valid', () => assert.equal(guard({items:[]},note,labels).rejected.length,0));
check('Invalid note type rejected', () => assert.equal(guard({items:[item()]},null,labels).accepted.length,0));
check('LLM-only term requires status choice', () => { const a=combine([],g(item()).accepted)[0];assert.equal(a.status,'conflict');assert.equal(a.field,'unclear'); });
check('Hybrid retains both original quotes', () => {const a=combine([{label:'fever',assertion:'stated',field:'suggested',evidence:'fever'}],g(item()).accepted)[0];assert.equal(a.evidence.classifier,'fever');assert.equal(a.evidence.llm,item().evidence);});
check('Hybrid agreement never resolves existing uncertainty', () => assert.equal(combine([{label:'fever',assertion:'stated',field:'unclear'}],g(item()).accepted)[0].field,'unclear'));
check('Hybrid disagreement requires choice', () => {const a=combine([{label:'fever',assertion:'denied',field:'suggested'}],g(item()).accepted)[0];assert.equal(a.status,'conflict');assert.equal(a.field,'unclear');});
check('Exact unrelated quote is structurally accepted (semantic limit)', () => assert.equal(g(item({evidence:'Mother has cough',duration_days:null})).accepted.length,1));
const result={created_by:'ChatGPT / Codex',created_at:new Date().toISOString(),module:target.pathname,source_sha256:createHash('sha256').update(readFileSync(target)).digest('hex'),test_sha256:createHash('sha256').update(readFileSync(new URL(import.meta.url))).digest('hex'),passed:tests.filter(t=>t.pass).length,total:tests.length,tests};
if(arg('--report')) {const p=arg('--report');mkdirSync(new URL('.',pathToFileURL(p)),{recursive:true});writeFileSync(p,JSON.stringify(result,null,2)+'\n');}
console.log(JSON.stringify(result,null,2));
if(result.passed!==result.total) process.exitCode=1;
